"""Persistence ports. Production adapters can implement these with SQLAlchemy, SQLModel, etc."""

from __future__ import annotations

from typing import Iterable, List, Optional, Protocol, Set

from auth_hub.domain.models import ModuleDefinition, Organization, Permission, Role, User


class AuthHubRepository(Protocol):
    def get_user(self, user_id: str) -> Optional[User]: ...
    def get_user_by_username(self, username: str) -> Optional[User]: ...
    def save_user(self, user: User) -> User: ...
    def list_users(self) -> List[User]: ...
    def get_organization(self, organization_id: str) -> Optional[Organization]: ...
    def save_organization(self, organization: Organization) -> Organization: ...
    def list_organizations(self) -> List[Organization]: ...
    def get_role(self, role_id: str) -> Optional[Role]: ...
    def get_role_by_code(self, code: str) -> Optional[Role]: ...
    def save_role(self, role: Role) -> Role: ...
    def list_roles(self) -> List[Role]: ...
    def get_permission(self, code: str) -> Optional[Permission]: ...
    def save_permission(self, permission: Permission) -> Permission: ...
    def list_permissions(self) -> List[Permission]: ...
    def save_module(self, module: ModuleDefinition) -> ModuleDefinition: ...
    def get_module(self, module_id: str) -> Optional[ModuleDefinition]: ...
    def list_modules(self) -> List[ModuleDefinition]: ...
    def assign_role(self, user_id: str, role_id: str) -> None: ...
    def assign_permission(self, role_id: str, permission_code: str) -> None: ...
    def user_role_ids(self, user_id: str) -> Set[str]: ...
    def role_permission_codes(self, role_id: str) -> Set[str]: ...
    def user_organization_ids(self, user_id: str) -> Set[str]: ...
    def assign_organization(self, user_id: str, organization_id: str) -> None: ...

