"""Persistence ports. Production adapters can implement these with SQLAlchemy, SQLModel, etc."""

from __future__ import annotations

from typing import Iterable, List, Optional, Protocol, Set

from auth_hub.domain.models import ModuleDefinition, Organization, Permission, ResourceDefinition, ResourceInstance, ResourceInstanceGrant, Role, User


class AuthHubRepository(Protocol):
    def get_user(self, user_id: str) -> Optional[User]: ...
    def get_user_by_username(self, username: str) -> Optional[User]: ...
    def save_user(self, user: User) -> User: ...
    def list_users(self) -> List[User]: ...
    def get_organization(self, organization_id: str) -> Optional[Organization]: ...
    def save_organization(self, organization: Organization) -> Organization: ...
    def delete_organization(self, organization_id: str) -> None: ...
    def list_organizations(self) -> List[Organization]: ...
    def get_role(self, role_id: str) -> Optional[Role]: ...
    def get_role_by_code(self, code: str) -> Optional[Role]: ...
    def save_role(self, role: Role) -> Role: ...
    def delete_role(self, role_id: str) -> None: ...
    def list_roles(self) -> List[Role]: ...
    def get_permission(self, code: str) -> Optional[Permission]: ...
    def save_permission(self, permission: Permission) -> Permission: ...
    def delete_permission(self, code: str) -> None: ...
    def list_permissions(self) -> List[Permission]: ...
    def get_resource(self, resource_id: str) -> Optional[ResourceDefinition]: ...
    def save_resource(self, resource: ResourceDefinition) -> ResourceDefinition: ...
    def delete_resource(self, resource_id: str) -> None: ...
    def list_resources(self, module_id: Optional[str] = None) -> List[ResourceDefinition]: ...
    def get_resource_instance(self, instance_id: str) -> Optional[ResourceInstance]: ...
    def get_resource_instance_by_external_id(self, resource_id: str, external_id: str) -> Optional[ResourceInstance]: ...
    def save_resource_instance(self, instance: ResourceInstance) -> ResourceInstance: ...
    def delete_resource_instance(self, instance_id: str) -> None: ...
    def list_resource_instances(self, resource_id: Optional[str] = None, *, owner_user_id: Optional[str] = None, organization_id: Optional[str] = None) -> List[ResourceInstance]: ...
    def replace_resource_instance_grants(self, resource_instance_id: str, grants: List[ResourceInstanceGrant]) -> List[ResourceInstanceGrant]: ...
    def list_resource_instance_grants(self, resource_instance_id: str) -> List[ResourceInstanceGrant]: ...
    def has_resource_instance_grant(self, resource_instance_id: str, user_id: str, permission_code: str) -> bool: ...
    def save_module(self, module: ModuleDefinition) -> ModuleDefinition: ...
    def delete_module(self, module_id: str) -> None: ...
    def get_module(self, module_id: str) -> Optional[ModuleDefinition]: ...
    def list_modules(self) -> List[ModuleDefinition]: ...
    def assign_role(self, user_id: str, role_id: str) -> None: ...
    def remove_role(self, user_id: str, role_id: str) -> None: ...
    def assign_permission(self, role_id: str, permission_code: str) -> None: ...
    def remove_permission(self, role_id: str, permission_code: str) -> None: ...
    def user_role_ids(self, user_id: str) -> Set[str]: ...
    def role_permission_codes(self, role_id: str) -> Set[str]: ...
    def user_organization_ids(self, user_id: str) -> Set[str]: ...
    def assign_organization(self, user_id: str, organization_id: str) -> None: ...
    def remove_organization(self, user_id: str, organization_id: str) -> None: ...
