"""Infrastructure service ports injected by the host application."""

from __future__ import annotations

from typing import Any, Mapping, Optional, Protocol, Sequence

from auth_hub.domain.models import AuditEvent, User


class Cache(Protocol):
    def get(self, key: str) -> Optional[Any]: ...
    def set(self, key: str, value: Any, ttl_seconds: int) -> None: ...
    def delete(self, key: str) -> None: ...


class TokenService(Protocol):
    def issue(self, user: User) -> Mapping[str, Any]: ...
    def refresh(self, refresh_token: str) -> Mapping[str, Any]: ...
    def revoke(self, access_token: str) -> None: ...
    def authenticate(self, access_token: str) -> Optional[str]: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class AuditLog(Protocol):
    def append(self, event: AuditEvent) -> None: ...

